# Generated by Django 5.0.4 on 2024-04-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_estudiente_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_nacimiento',
        ),
    ]
